In [113]:
from IPython.display import HTML
HTML("""
<p style="text-align: left">
    <b><font color='red'>ABOUT DATASET !</font></b>
     <br></br>
     <P><font color='white' , font-family: sans-serif>This dataset is a collection of data that includes information on the sales of Adidas products.</font></P>
</p>
  """)

In [114]:
Link_of_data = {"This is the link of the dataset : " : "https://www.kaggle.com/datasets/heemalichaudhari/adidas-sales-dataset",
                "  The source of this dataset is : " :"Kaggle" }
Link_of_data = Link_of_data.items()

for (keys, values) in Link_of_data:
    print(keys, values)

This is the link of the dataset :  https://www.kaggle.com/datasets/heemalichaudhari/adidas-sales-dataset
  The source of this dataset is :  Kaggle

In [115]:
"""
Data Description :

Retailer:         The company or group that sells Adidas goods.
Retailer ID:      a unique number that each merchant is given.
Invoice Date:     The date when the sales transaction occurred.
Region:           The store's operational geographic territory.
State:            The state within the region where the retailer is located.
City:             The retailer's location in the city.
Product:          The item for sale is an Adidas product.
Price per Unit:   The price of a single Adidas product unit.
Units Sold:       The amount of Adidas merchandise sold in a certain transaction, expressed in units.
Total Sales:      The amount of money made from the sale of Adidas goods in a certain transaction.
Operating Profit: The amount of money made from the sale of Adidas goods in a certain transaction.
Operating Margin: The proportion of operational profit to overall sales.
Sales Method:     The process used to carry out the sales transaction.

"""

"\nData Description :\n\nRetailer:         The company or group that sells Adidas goods.\nRetailer ID:      a unique number that each merchant is given.\nInvoice Date:     The date when the sales transaction occurred.\nRegion:           The store's operational geographic territory.\nState:            The state within the region where the retailer is located.\nCity:             The retailer's location in the city.\nProduct:          The item for sale is an Adidas product.\nPrice per Unit:   The price of a single Adidas product unit.\nUnits Sold:       The amount of Adidas merchandise sold in a certain transaction, expressed in units.\nTotal Sales:      The amount of money made from the sale of Adidas goods in a certain transaction.\nOperating Profit: The amount of money made from the sale of Adidas goods in a certain transaction.\nOperating Margin: The proportion of operational profit to overall sales.\nSales Method:     The process used to carry out the sales transaction.\n\n"

## Some data preprocessing:

In [116]:
import pandas as pd 
import numpy as np 
import plotly.express as px
import plotly.graph_objects as go
import plotly.subplots as ps
from plotly.subplots import make_subplots

In [117]:
# Reading XLSX : 
Adidas = pd.read_excel(r"c:\Users\ooo\Downloads\archive(41)\Adidas US Sales Datasets.xlsx")

In [118]:
#CHECK!
Adidas.shape

(9652, 14)

In [119]:
#CHECK!
Adidas.duplicated().sum()

1

In [120]:
Adidas.isna().sum()

Unnamed: 0     9652
Unnamed: 1        3
Unnamed: 2        2
Unnamed: 3        3
Unnamed: 4        3
Unnamed: 5        3
Unnamed: 6        3
Unnamed: 7        3
Unnamed: 8        3
Unnamed: 9        3
Unnamed: 10       3
Unnamed: 11       3
Unnamed: 12       3
Unnamed: 13       3
dtype: int64

In [121]:
#CHECK!
Adidas.drop_duplicates()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,NaN,Adidas Sales Database,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
4,NaN,Foot Locker,1185732,2020-01-01 00:00:00,Northeast,New York,New York,Men's Street Footwear,50,1200,600000,300000,0.5,In-store
5,NaN,Foot Locker,1185732,2020-01-02 00:00:00,Northeast,New York,New York,Men's Athletic Footwear,50,1000,500000,150000,0.3,In-store
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9647,NaN,Foot Locker,1185732,2021-01-24 00:00:00,Northeast,New Hampshire,Manchester,Men's Apparel,50,64,3200,896.0,0.28,Outlet
9648,NaN,Foot Locker,1185732,2021-01-24 00:00:00,Northeast,New Hampshire,Manchester,Women's Apparel,41,105,4305,1377.6,0.32,Outlet
9649,NaN,Foot Locker,1185732,2021-02-22 00:00:00,Northeast,New Hampshire,Manchester,Men's Street Footwear,41,184,7544,2791.28,0.37,Outlet
9650,NaN,Foot Locker,1185732,2021-02-22 00:00:00,Northeast,New Hampshire,Manchester,Men's Athletic Footwear,42,70,2940,1234.8,0.42,Outlet
9651,NaN,Foot Locker,1185732,2021-02-22 00:00:00,Northeast,New Hampshire,Manchester,Women's Street Footwear,29,83,2407,649.89,0.27,Outlet

In [122]:
#CHECK!
Adidas.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13'],
      dtype='object')

In [123]:
#Remove the First 3 rows :
Adidas = Adidas.drop(Adidas.index[:3])

In [124]:
#Drop the first colums:
Adidas.drop("Unnamed: 0", axis = 1, inplace = True)

In [125]:
#Change the column names :
Adidas.columns = Adidas.iloc[0]

In [126]:
#CHECK!
Adidas.head()

3,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
3,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
4,Foot Locker,1185732,2020-01-01 00:00:00,Northeast,New York,New York,Men's Street Footwear,50,1200,600000,300000,0.5,In-store
5,Foot Locker,1185732,2020-01-02 00:00:00,Northeast,New York,New York,Men's Athletic Footwear,50,1000,500000,150000,0.3,In-store
6,Foot Locker,1185732,2020-01-03 00:00:00,Northeast,New York,New York,Women's Street Footwear,40,1000,400000,140000,0.35,In-store
7,Foot Locker,1185732,2020-01-04 00:00:00,Northeast,New York,New York,Women's Athletic Footwear,45,850,382500,133875,0.35,In-store

In [127]:
 #Drop the first row :
Adidas = Adidas.drop(Adidas.index[0])

In [128]:
#CHECK!
Adidas.head()

3,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
4,Foot Locker,1185732,2020-01-01 00:00:00,Northeast,New York,New York,Men's Street Footwear,50,1200,600000,300000,0.5,In-store
5,Foot Locker,1185732,2020-01-02 00:00:00,Northeast,New York,New York,Men's Athletic Footwear,50,1000,500000,150000,0.3,In-store
6,Foot Locker,1185732,2020-01-03 00:00:00,Northeast,New York,New York,Women's Street Footwear,40,1000,400000,140000,0.35,In-store
7,Foot Locker,1185732,2020-01-04 00:00:00,Northeast,New York,New York,Women's Athletic Footwear,45,850,382500,133875,0.35,In-store
8,Foot Locker,1185732,2020-01-05 00:00:00,Northeast,New York,New York,Men's Apparel,60,900,540000,162000,0.3,In-store

In [129]:
#Reset  Index :
Adidas = Adidas.reset_index(drop=True)

In [130]:
#CHECK!
Adidas.columns

Index(['Retailer', 'Retailer ID', 'Invoice Date', 'Region', 'State', 'City',
       'Product', 'Price per Unit', 'Units Sold', 'Total Sales',
       'Operating Profit', 'Operating Margin', 'Sales Method'],
      dtype='object', name=3)

In [131]:
#CHECK!
Adidas.head()

3,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
0,Foot Locker,1185732,2020-01-01 00:00:00,Northeast,New York,New York,Men's Street Footwear,50,1200,600000,300000,0.5,In-store
1,Foot Locker,1185732,2020-01-02 00:00:00,Northeast,New York,New York,Men's Athletic Footwear,50,1000,500000,150000,0.3,In-store
2,Foot Locker,1185732,2020-01-03 00:00:00,Northeast,New York,New York,Women's Street Footwear,40,1000,400000,140000,0.35,In-store
3,Foot Locker,1185732,2020-01-04 00:00:00,Northeast,New York,New York,Women's Athletic Footwear,45,850,382500,133875,0.35,In-store
4,Foot Locker,1185732,2020-01-05 00:00:00,Northeast,New York,New York,Men's Apparel,60,900,540000,162000,0.3,In-store

In [132]:
#CHECK!
Adidas.shape

(9648, 13)

In [133]:
#CHECK!
Adidas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9648 entries, 0 to 9647
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Retailer          9648 non-null   object
 1   Retailer ID       9648 non-null   object
 2   Invoice Date      9648 non-null   object
 3   Region            9648 non-null   object
 4   State             9648 non-null   object
 5   City              9648 non-null   object
 6   Product           9648 non-null   object
 7   Price per Unit    9648 non-null   object
 8   Units Sold        9648 non-null   object
 9   Total Sales       9648 non-null   object
 10  Operating Profit  9648 non-null   object
 11  Operating Margin  9648 non-null   object
 12  Sales Method      9648 non-null   object
dtypes: object(13)
memory usage: 980.0+ KB

In [134]:
# Invoice Date to datetime:
Adidas['Invoice Date']=pd.to_datetime(Adidas['Invoice Date'])

In [135]:
#Units sold to int :
Adidas['Units Sold'] = Adidas['Units Sold'].astype("int")

In [136]:
#Price per Unit, Total Sales,Operating Profit & Operating Margin to float :
Adidas[['Price per Unit', 'Total Sales','Operating Profit', 'Operating Margin']] = Adidas[['Price per Unit', 'Total Sales','Operating Profit', 'Operating Margin']].astype("float")

In [137]:
#CHECK!
Adidas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9648 entries, 0 to 9647
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Retailer          9648 non-null   object
 1   Retailer ID       9648 non-null   object
 2   Invoice Date      9648 non-null   datetime64[ns]
 3   Region            9648 non-null   object
 4   State             9648 non-null   object
 5   City              9648 non-null   object
 6   Product           9648 non-null   object
 7   Price per Unit    9648 non-null   float64
 8   Units Sold        9648 non-null   int32
 9   Total Sales       9648 non-null   float64
 10  Operating Profit  9648 non-null   float64
 11  Operating Margin  9648 non-null   float64
 12  Sales Method      9648 non-null   object
dtypes: datetime64[ns](1), float64(4), int32(1), object(7)
memory usage: 942.3+ KB

In [138]:
#Make new columns for analysis :
Adidas['Year'] = Adidas['Invoice Date'].dt.year
Adidas['Month'] = Adidas['Invoice Date'].dt.month
Adidas['Day'] = Adidas['Invoice Date'].dt.day

In [139]:
#Divide the year into two halves :
Adidas['Calendering Year'] = pd.cut(Adidas['Month'],2,labels=["First Half","Second Half"])

In [140]:
#CHECK!
Adidas.describe()

3,Invoice Date,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Year,Month,Day
count,9648,9648.000000,9648.000000,9648.000000,9648.000000,9648.000000,9648.000000,9648.000000,9648.000000
mean,2021-05-10 15:20:44.776119296,45.216625,256.930037,93273.437500,34425.244761,0.422991,2020.865050,6.458126,14.696310
min,2020-01-01 00:00:00,7.000000,0.000000,0.000000,0.000000,0.100000,2020.000000,1.000000,1.000000
25%,2021-02-17 00:00:00,35.000000,106.000000,4254.500000,1921.752500,0.350000,2021.000000,3.000000,9.000000
50%,2021-06-04 00:00:00,45.000000,176.000000,9576.000000,4371.420000,0.410000,2021.000000,6.000000,15.000000
75%,2021-09-16 00:00:00,55.000000,350.000000,150000.000000,52062.500000,0.490000,2021.000000,9.000000,21.000000
max,2021-12-31 00:00:00,110.000000,1275.000000,825000.000000,390000.000000,0.800000,2021.000000,12.000000,31.000000
std,NaN,14.705397,214.252030,141916.016727,54193.113713,0.097197,0.341688,3.454799,7.348019

In [141]:
#CHECK!
Adidas.describe(include = 'O')

3,Retailer,Retailer ID,Region,State,City,Product,Sales Method
count,9648,9648,9648,9648,9648,9648,9648
unique,6,4,5,50,52,6,3
top,Foot Locker,1185732,West,California,Portland,Men's Street Footwear,Online
freq,2637,5265,2448,432,360,1610,4889

## Univariant Analysis:

In [142]:
Adidas.head()

3,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method,Year,Month,Day,Calendering Year
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.0,0.50,In-store,2020,1,1,First Half
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.0,0.30,In-store,2020,1,2,First Half
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.0,0.35,In-store,2020,1,3,First Half
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,382500.0,133875.0,0.35,In-store,2020,1,4,First Half
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000.0,162000.0,0.30,In-store,2020,1,5,First Half

In [143]:
Adidas['Retailer'].unique()

array(['Foot Locker', 'Walmart', 'Sports Direct', 'West Gear', "Kohl's",
       'Amazon'], dtype=object)

In [144]:
Retailer = Adidas['Retailer'].value_counts().reset_index()
Retailer

        Retailer  count
0    Foot Locker   2637
1      West Gear   2374
2  Sports Direct   2032
3         Kohl's   1030
4         Amazon    949
5        Walmart    626

In [145]:
night_colors = ['rgb(56, 75, 126)', 'rgb(18, 36, 37)', 'rgb(34, 53, 101)','rgb(36, 55, 57)', 'rgb(6, 4, 4)']
blue_colors = ['cyan','royalblue','darkblue','lightsalmon']
sunflowers_colors = ['rgb(177, 127, 38)', 'rgb(205, 152, 36)', 'rgb(99, 79, 37)',
                     'rgb(129, 180, 179)', 'rgb(124, 103, 37)']
irises_colors = ['rgb(33, 75, 99)', 'rgb(79, 129, 102)', 'rgb(151, 179, 100)',
                 'rgb(175, 49, 35)', 'rgb(36, 73, 147)']
cafe_colors =  ['rgb(146, 123, 21)', 'rgb(177, 180, 34)', 'rgb(206, 206, 40)',
                'rgb(175, 51, 21)', 'rgb(35, 36, 21)']

### Analyze the top retailers:

In [146]:
labels = ['Foot Locker', 'Walmart', 'Sports Direct', 'West Gear', "Kohl's", 'Amazon']
values = [2637, 2374, 2032, 1030 ,949, 626]
Retailer_pie = go.Figure(data=[go.Pie( labels=labels , values= values , marker_colors = night_colors , pull=[0.3, 0, 0, 0 ,0, 0])])
Retailer_pie.update(layout_title_text='Retailers Share')
Retailer_pie.show()

### Analyze the most active cities on both year:

In [280]:
city = Adidas['City'].value_counts().nlargest(10).reset_index()
city

             City  count
0        Portland    360
1      Charleston    288
2         Orlando    216
3  Salt Lake City    216
4         Houston    216
5           Boise    216
6         Phoenix    216
7     Albuquerque    216
8         Atlanta    216
9        New York    216

In [148]:
city_histogram = px.histogram(city , x = 'City' , y = 'count', color = 'City',color_discrete_sequence = blue_colors , title= 'Cities took large Market area')
city_histogram.show()

### Wich sales method was preferred ?

In [149]:
Method = Adidas['Sales Method'].value_counts().reset_index()
Method

  Sales Method  count
0       Online   4889
1       Outlet   3019
2     In-store   1740

In [150]:
Method_bar =  px.bar(Method , x = 'Sales Method', y ='count', color = 'Sales Method', color_discrete_sequence = px.colors.sequential.RdBu , title = 'Which sales method is preferred ?')
Method_bar.show()

### Analyze the most desired products by the market:

In [151]:
Product = Adidas['Product'].value_counts().reset_index()
Product

                     Product  count
0      Men's Street Footwear   1610
1    Men's Athletic Footwear   1610
2    Women's Street Footwear   1608
3            Women's Apparel   1608
4  Women's Athletic Footwear   1606
5              Men's Apparel   1606

In [152]:
Product_pie = px.pie(Product , names = 'Product', values ='count' ,hole = .3 , title = 'What are the most desired categories of products?',color_discrete_sequence = night_colors)
Product_pie.show()

### Analyze the most active cities in each year:

In [251]:
city_2020 = Adidas[Adidas['Year'] == 2020]['City'].value_counts().sort_values(ascending=False).reset_index()
city_2020

            City  count
0       New York    216
1        Houston    216
2      Las Vegas    216
3         Denver    144
4        Seattle    144
5          Miami    144
6    Minneapolis    144
7  San Francisco     63
8   Philadelphia     15

In [235]:
city2020_fig = px.bar(city_2020 , x = 'City' , y = 'count',title = 'The Most Active Cities In 2020')
city2020_fig.show()

In [232]:
city_2021 = Adidas[Adidas['Year'] == 2021]['City'].value_counts().nlargest(9).reset_index()
city_2021

             City  count
0        Portland    360
1      Charleston    288
2     Albuquerque    216
3  Salt Lake City    216
4      Burlington    216
5          Boston    216
6      Providence    216
7        Hartford    216
8   Oklahoma City    216

In [236]:
city2021_fig = px.bar(city_2021 , x = 'City' , y = 'count' ,title = 'The Most Active Cities In 2021')
city2021_fig.show()

In [153]:
"""
Insights from univariant analysis :
* Most retailers are Foot Locker ,  Walmart , Sports Direct.
* Most Customers are in Poland and Charleston cities.
"""

'\nInsights from univariant analysis :\n* Most retailers are Foot Locker ,  Walmart , Sports Direct.\n* Most Customers are in Poland and Charleston cities.\n* Most preferred method by customers is online sales.\n* Most desired products are shoes and boots with approximately same percentages.\n'

## Bivariant  and Mulivariant Analysis :

In [154]:
Adidas.head()

3,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method,Year,Month,Day,Calendering Year
0,Foot Locker,1185732,2020-01-01,Northeast,New York,New York,Men's Street Footwear,50.0,1200,600000.0,300000.0,0.50,In-store,2020,1,1,First Half
1,Foot Locker,1185732,2020-01-02,Northeast,New York,New York,Men's Athletic Footwear,50.0,1000,500000.0,150000.0,0.30,In-store,2020,1,2,First Half
2,Foot Locker,1185732,2020-01-03,Northeast,New York,New York,Women's Street Footwear,40.0,1000,400000.0,140000.0,0.35,In-store,2020,1,3,First Half
3,Foot Locker,1185732,2020-01-04,Northeast,New York,New York,Women's Athletic Footwear,45.0,850,382500.0,133875.0,0.35,In-store,2020,1,4,First Half
4,Foot Locker,1185732,2020-01-05,Northeast,New York,New York,Men's Apparel,60.0,900,540000.0,162000.0,0.30,In-store,2020,1,5,First Half

### Analyze the Average of profits in each year according to the sale method:

In [155]:
Method_Profit_year = Adidas.groupby(['Year','Sales Method'])['Operating Profit'].mean().reset_index()
Method_Profit_year

   Year Sales Method  Operating Profit
0  2020     In-store     110089.024390
1  2020       Online       3993.370264
2  2020       Outlet      61162.116165
3  2021     In-store      66067.266001
4  2021       Online      21665.219140
5  2021       Outlet      30909.499266

In [156]:
Method_Profit_year = px.histogram(Method_Profit_year, x = 'Sales Method' , y = 'Operating Profit' ,title = 'AVG profits per sales method', color='Year' , color_discrete_sequence = blue_colors)
Method_Profit_year.show()

### Analyze the total profit generated by each retailer in each year:

In [157]:
Retailers_profit_2020 = Adidas[Adidas['Year'] == 2020].groupby(['Year','Retailer'])['Total Sales'].sum().sort_values(ascending = False).reset_index()
Retailers_profit_2020

   Year       Retailer  Total Sales
0  2020      West Gear   90299266.0
1  2020    Foot Locker   42876805.0
2  2020        Walmart   32885000.0
3  2020  Sports Direct   15261101.0
4  2020         Kohl's     758503.0

In [158]:
Retailers_profit_2021 = Adidas[Adidas['Year'] == 2021].groupby(['Year','Retailer'])['Total Sales'].sum().sort_values(ascending = False).reset_index()
Retailers_profit_2021

   Year       Retailer  Total Sales
0  2021    Foot Locker  177217915.0
1  2021  Sports Direct  167209896.0
2  2021      West Gear  152665067.0
3  2021         Kohl's  101356250.0
4  2021         Amazon   77698912.0
5  2021        Walmart   41673410.0

In [159]:
fig = make_subplots(rows=1, cols=2, shared_yaxes=True)
fig.add_trace(go.Bar( x= Retailers_profit_2020['Retailer'], y= Retailers_profit_2020['Total Sales'] , name ='Market Share of each retailers in 2020', marker_color= night_colors), 1 , 1 )
fig.add_trace(go.Bar( x= Retailers_profit_2021['Retailer'], y= Retailers_profit_2021['Total Sales'] , name ='Market Share  of each retailers in 2021', marker_color=blue_colors), 1 , 2 )
fig.update_layout(height=500, width=1200, title_text="Profits for each retailers in 2020 and 2021 ")
fig.show()

### Analyze why the Total sales was law in 2020 (Price per unit upon time) :

In [160]:
price_per_unit_year = Adidas.groupby(['Year','Month'])['Price per Unit'].mean().reset_index()
price_per_unit_year

    Year  Month  Price per Unit
0   2020      1       47.186667
1   2020      2       55.412281
2   2020      3       50.038168
3   2020      4       58.215385
4   2020      5       59.463158
5   2020      6       64.533333
6   2020      7       56.605769
7   2020      8       41.201439
8   2020      9       48.666667
9   2020     10       42.639535
10  2020     11       43.828571
11  2020     12       47.021739
12  2021      1       38.220816
13  2021      2       36.632931
14  2021      3       35.371088
15  2021      4       38.322082
16  2021      5       45.110345
17  2021      6       48.147982
18  2021      7       51.959701
19  2021      8       46.498599
20  2021      9       41.497253
21  2021     10       44.432692
22  2021     11       50.213043
23  2021     12       56.656672

In [167]:
fig = px.line(price_per_unit_year , x = 'Month', y = 'Price per Unit', color = 'Year', color_discrete_map = {2020:'rgb(175, 49, 35)' , 2021:'rgb(36, 73, 147)'},
title= 'Average of prices over the years 2020 and 2021' , markers = True)
fig.show()

### Tracking the total sales over the years 2020 and 2021 :

In [168]:
Total_Sales_year = Adidas.groupby(['Year','Month'])['Total Sales'].sum().reset_index()
Total_Sales_year

    Year  Month  Total Sales
0   2020      1   16253746.0
1   2020      2   14997988.0
2   2020      3   17660577.0
3   2020      4   24607006.0
4   2020      5   16918014.0
5   2020      6    8829819.0
6   2020      7   17146013.0
7   2020      8   19877980.0
8   2020      9   18304436.0
9   2020     10   10836269.0
10  2020     11    8622300.0
11  2020     12    8026527.0
12  2021      1   55225396.0
13  2021      2   46102165.0
14  2021      3   39148532.0
15  2021      4   47732964.0
16  2021      5   63589681.0
17  2021      6   65917553.0
18  2021      7   78334681.0
19  2021      8   72288221.0
20  2021      9   59357023.0
21  2021     10   53074764.0
22  2021     11   59235040.0
23  2021     12   77815430.0

In [210]:
fig = px.line(Total_Sales_year , x = 'Month', y = 'Total Sales', color = 'Year', color_discrete_map = {2020:'rgb(175, 49, 35)' , 2021:'rgb(36, 73, 147)'},
title= 'Total Sales over the years 2020 and 2021' , markers = True)

fig.show()

### Tracking the profits over the years 2020 and 2021 :

In [171]:
profit_year = Adidas.groupby(['Year','Month'])['Operating Margin'].sum().reset_index()
profit_year

    Year  Month  Operating Margin
0   2020      1             62.47
1   2020      2             46.12
2   2020      3             50.10
3   2020      4             56.66
4   2020      5             37.92
5   2020      6             19.42
6   2020      7             37.92
7   2020      8             59.34
8   2020      9             41.82
9   2020     10             36.42
10  2020     11             40.54
11  2020     12             36.93
12  2021      1            293.85
13  2021      2            272.97
14  2021      3            284.65
15  2021      4            305.36
16  2021      5            311.22
17  2021      6            283.43
18  2021      7            285.28
19  2021      8            308.59
20  2021      9            324.22
21  2021     10            316.03
22  2021     11            289.18
23  2021     12            280.58

In [172]:
fig = px.line(profit_year , x = 'Month', y = 'Operating Margin', color = 'Year', color_discrete_map = {2020:'rgb(175, 49, 35)' , 2021:'rgb(36, 73, 147)'},
title= 'Profit over the years 2020 and 2021' , markers = True)
fig.show()

### Analyze units sold according to the year halves:

In [173]:
Units_sold_in_each_half = Adidas.groupby(['Year','Calendering Year'])['Units Sold'].sum().reset_index()
Units_sold_in_each_half

   Year Calendering Year  Units Sold
0  2020       First Half      239834
1  2020      Second Half      222515
2  2021       First Half      984762
3  2021      Second Half     1031750

In [174]:
fig = px.sunburst(Units_sold_in_each_half,
                  path = ['Year', 'Calendering Year'],
                  values = 'Units Sold',
                  color_discrete_sequence = ['blue'],
                  title=' Units Sold Over each half of the Years 2020 and 2021 ')
fig.show()

### Analyze the sale method of Portland & Charleston:

In [307]:
high_sales_cities = Adidas[(Adidas['City'] == 'Portland') |( Adidas['City'] == 'Charleston')]
Port_Char = high_sales_cities.groupby('City')['Sales Method'].value_counts().reset_index()
Port_Char

         City Sales Method  count
0  Charleston       Online    216
1  Charleston     In-store     72
2    Portland       Online    144
3    Portland       Outlet    144
4    Portland     In-store     72

In [309]:
Port_Char_fig = px.sunburst(Port_Char, path=['City','Sales Method'] , values='count', title= 'The Sales Method By PORT. & CHAR.' ,color_discrete_sequence = px.colors.sequential.RdBu)
Port_Char_fig

### Analyze the profits from the top retailers of the top states:

In [177]:
Profit_state = Adidas[(Adidas['City'] == 'Portland' )| (Adidas['City'] == 'Charleston') ].groupby(['Sales Method','City','State','Retailer'])['Operating Profit'].mean().nlargest(20).sort_values(ascending = False).reset_index()
Profit_state

   Sales Method        City           State       Retailer  Operating Profit
0      In-store    Portland          Oregon      West Gear      98997.395833
1        Online  Charleston  South Carolina    Foot Locker      81549.967034
2      In-store  Charleston   West Virginia    Foot Locker      66153.947368
3        Online  Charleston  South Carolina  Sports Direct      65436.164615
4      In-store  Charleston   West Virginia      West Gear      54440.094340
5        Outlet    Portland           Maine         Amazon      43288.419118
6        Outlet    Portland           Maine      West Gear      33515.625000
7        Online    Portland          Oregon      West Gear       3504.667083
8        Outlet    Portland          Oregon      West Gear       2680.506528
9        Online  Charleston   West Virginia    Foot Locker       2218.887895
10       Online  Charleston   West Virginia      West Gear       1859.336792
11       Online    Portland           Maine         Amazon       1538.912794
12       Online    Portland           Maine      West Gear       1333.325000

In [178]:
Fig1 = px.histogram(Profit_state , x = 'Operating Profit' , y = 'State' , color_discrete_sequence = blue_colors , color = 'Retailer')
Fig1.show()

In [179]:
fig2 = px.histogram(Profit_state , x = 'Operating Profit' , y = 'State'  , color_discrete_sequence = irises_colors , color = 'Sales Method')
fig2.show()

### Analyze the highest profit cities  of 2020 & 2021:

In [267]:
city_state2020 = Adidas[Adidas['Year'] == 2020].groupby(['City','State'])['Operating Margin'].sum().sort_values(ascending=False).reset_index()
city_state2020

            City         State  Operating Margin
0        Houston         Texas             94.15
1      Las Vegas        Nevada             87.68
2       New York      New York             85.62
3          Miami       Florida             61.80
4         Denver      Colorado             61.50
5    Minneapolis     Minnesota             58.77
6        Seattle    Washington             46.81
7  San Francisco    California             23.35
8   Philadelphia  Pennsylvania              5.98

In [293]:
city_state2020_fig = px.bar(city_state2020, x = 'State', y = 'Operating Margin',color_discrete_sequence = ['rgb(33, 75, 99)'])  
city_state2020_fig

In [296]:
city_state2021 = Adidas[Adidas['Year'] == 2021].groupby(['City','State'])['Operating Margin'].sum().sort_values(ascending=False).nlargest(9).reset_index()
city_state2021

             City        State  Operating Margin
0      Birmingham      Alabama            119.57
1       Knoxville    Tennessee            109.42
2          Dallas        Texas             99.88
3           Boise        Idaho             99.13
4         Jackson  Mississippi             98.13
5     New Orleans    Louisiana             96.52
6  Salt Lake City         Utah             96.05
7      Burlington      Vermont             95.96
8     Little Rock     Arkansas             95.15

In [297]:
city_state2021_fig = px.bar(city_state2021, x = 'State', y = 'Operating Margin',color_discrete_sequence = ['rgb(33, 75, 99)'])  
city_state2021_fig

In [ ]:
"""
insights:
* Customers Total sales increased in 2020 by (west gear) and in 2021 by (Foot Locker), specially (in store method and outlet).
* Amazon was not there in 2020 .
* Average of prices per unit in 2020 increased on the first half of the year and then decreased, but in 2021 increased at the second half of the year, and no
     *big variationin prices as 2020. so generally, the products were expensive , it may be due to corona virus on that year.
*Although there was variation in prices but the units sold in two halves of years 2020 ,2021 were of approximate rate.
*The track of the best profit margin is South Charleston , South Carolina  , Foot Locker , Online .
* 2020 : Prices rised , then the total sales decreased which led to dropping the profit.
* 2021 : Prices were constant and suitable , then the total sales increased which led to increasing the profit.
"""